version: '3.4'

services:
  webapi:
    image: examplecrud/webapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7101:443"
    environment:
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx 
      - ConnectionStrings__WebApiConnection=169.254.160.23;Database=LAR_DB;User Id=WebApiLogin;Password=P@ssw0rd!2023; Trusted_Connection=True;TrustServerCertificate=True;MultipleActiveResultSets=true
    volumes:
      - ./certs:/https:ro
